### ISSUE TITLE
Update ruby version

### ISSUE THREAD

**Issue by jagthedrummer** [andrewmcodes/standardrb-action#21]
# Bug Report 

## Describe the bug

We've added this to a workflow and during the `Run andrewmcodes/standardrb-action@v1.0.0` step we're seeing this error:

```
ERROR:  Error installing standard:
	There are no versions of rubocop (~> 1.56.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	rubocop requires Ruby version >= 2.7.0. The current ruby version is 2.6.5.114.
```

It looks like the action is trying to install a version of rubocop that doesn't agree with the version of ruby that it runs on.

# To Reproduce

Add the action to a workflow.

# Expected behavior

The action should run without complaining about version incompatibilities.

## Stacktrace

```
Run andrewmcodes/standardrb-action@v1.0.0
/usr/bin/docker run --name ef7d85fac205452ca5414c9653741e5b8701fb_b98611 --label ef7d85 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/bullet_train-core/bullet_train-core":"/github/workspace" ef7d85:fac205452ca5414c9653741e5b8701fb
Successfully installed language_server-protocol-3.17.0.3
Building native extensions. This could take a while...
Successfully installed racc-1.7.1
Successfully installed ast-2.4.2
Successfully installed parser-3.2.2.3
Successfully installed rubocop-ast-1.29.0
Successfully installed unicode-display_width-2.4.2
Successfully installed ruby-progressbar-1.13.0
Successfully installed rexml-3.2.6
Successfully installed regexp_parser-2.8.1
Successfully installed rainbow-3.1.1
Successfully installed parallel-1.23.0
Building native extensions. This could take a while...
ERROR:  Error installing standard:
	There are no versions of rubocop (~> 1.56.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	rubocop requires Ruby version >= 2.7.0. The current ruby version is 2.6.5.114.
Successfully installed json-2.6.3
Successfully installed base64-0.1.1
```

## Action Version & Workflow File
 
 - Version `andrewmcodes/standardrb-action@v1.0.0`

### Workflow File

```yaml
name: "CI"

on:
  - "pull_request"

jobs:
  standard:
    name: "Standard"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andrewmcodes/standardrb-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by andrewmcodes** [comment]
@jagthedrummer you should be able to use `v2.0.0` now. Please note that I would not recommend using this action when you can now do:

```yaml
  standardrb:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec standardrb --format github --parallel
```

Which will create the annotations for you just like this action does but without the extra overhead.

**Comment by krystof-k** [comment]
Thanks @andrewmcodes. Here is my adjusted version, which installs just `standard` and `standard-rails` from Gemfile.lock:

```yaml
name: Standard Ruby
on: push
jobs:
  standard-ruby:
    name: Standard Ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: |
          ruby -e " \
            require 'bundler'; \
            lockfile = Bundler.read_file('Gemfile.lock'); \
            parser = Bundler::LockfileParser.new(lockfile); \
            standard_version = parser.specs.find { |spec| spec.name == 'standard' }&.version.to_s; \
            standard_rails_version = parser.specs.find { |spec| spec.name == 'standard-rails' }&.version.to_s; \
            puts(\"Found \`standard:#{standard_version}\` and \`standard-rails:#{standard_rails_version}\` in Gemfile.lock\"); \
            system('gem', 'install', 'standard', '-v', standard_version) if standard_version; \
            system('gem', 'install', 'standard-rails', '-v', standard_rails_version) if standard_rails_version; \
            "
      - run: standardrb --format github --parallel
```
