### ISSUE TITLE
Confusing local (Ruby 3.2.2) vs GitHub Actions (Ruby 3.1) Behaviour

### ISSUE THREAD

**Issue by smaboshe** [andrewmcodes/standardrb-action#22]
# Bug Report 

## Describe the bug

When working with `standard` locally, I run `bundle exec standardrb` or `bundle exec standardrb --fix`. On Ruby `3.2.2` projects, I am experiencing an issue where no formatting warnings are highlighted locally but the GitHub Actions fails. The Action also reports that it is running Ruby `3.1`. e.g.:

```
unexpected token tRPAREN
(Using Ruby 3.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)
```

This is despite having `TargetRubyVersion` in `.rubocop.yml`:
```
AllCops:
  TargetRubyVersion: 3.2.2
```

When downgrading the local project to Ruby `3.1`, I see lots of formatting warnings.

How can I ensure that `standardrb-action` is running the same version as a GitHub Action as it does on my local environment?

# To Reproduce

Using Ruby `3.2.2`, run `bundle exec standardrb --fix`, resolve issues on the project locally and then use the GitHub Action.

# Expected behavior

I expect the GitHub Action to not give any warnings (since it did not locally).

# Actual behaviour

The GitHub Action generates warnings and reports to be running Ruby `3.1`.

## Stacktrace

Not applicable

## Action Version & Workflow File
 
Not applicable

### Workflow File

```yaml
name: StandardRB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: StandardRB Linter
      uses: testdouble/standard-ruby-action@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Ref: https://github.com/testdouble/standard-ruby-action#package-example-workflow
