### ISSUE TITLE
Don't fail on warnings?

### ISSUE THREAD

**Issue by rsanheim** [andrewmcodes/standardrb-action#9]
Hey thanks for creating / maintaining this action. 

We are converting our project to be in line with standardrb, and as we do that we are often ignoring certain warnings, such as the "useless assignment variable", especially in specs where it is nice to have an explanatory name for a fixture.

Would it be possible to configure this action to not return a failure on warnings? If not, would you be open to a PR to add that functionality?

**Comment by andrewmcodes** [comment]
@rsanheim Definitely open to a PR. This library needs some love but I don’t have the time right now as I search for a new job.

**Comment by andrewmcodes** [comment]
This action is not actively maintained and thus isn't accepting new features. I would highly suggest replacing it with the following:

```yaml
  standardrb:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec standardrb --format github --parallel
```
